ARG ARTIFACTORY_HOST
ENV ARTIFACTORY_HOST=$ARTIFACTORY_HOST
ARG ARTIFACTORY_BASE_URL
ENV ARTIFACTORY_BASE_URL=$ARTIFACTORY_BASE_URL
ARG ARTIFACTORY_DEVELOPER_USERNAME
ENV ARTIFACTORY_DEVELOPER_USERNAME=$ARTIFACTORY_DEVELOPER_USERNAME
ARG ARTIFACTORY_DEVELOPER_PASSWORD
ENV ARTIFACTORY_DEVELOPER_PASSWORD=$ARTIFACTORY_DEVELOPER_PASSWORD
ARG ARTIFACTORY_RELEASER_USERNAME
ENV ARTIFACTORY_RELEASER_USERNAME=$ARTIFACTORY_RELEASER_USERNAME
ARG ARTIFACTORY_RELEASER_PASSWORD
ENV ARTIFACTORY_RELEASER_PASSWORD=$ARTIFACTORY_RELEASER_PASSWORD
ARG NEW_RELIC_PROXY_HOST
ENV NEW_RELIC_PROXY_HOST=$NEW_RELIC_PROXY_HOST
ARG NEW_RELIC_PROXY_PORT
ENV NEW_RELIC_PROXY_PORT=$NEW_RELIC_PROXY_PORT
ARG NEW_RELIC_LICENSE_KEY
ENV NEW_RELIC_LICENSE_KEY=$NR_LICENSEKEY
ENV NEWRELIC_APM_JAVA_HOME="/usr/local"
ENV NEWRELIC_APM_JAVA_VERSION="8.12.0"
ENV NEW_RELIC_APP_NAME="sample-java-proc"
ENV ARTIFACTORY_KEY=$ARTIFACTORY_KEY
# Downloading NR Agent 
RUN curl -L -H "X-JFrog-Art-Api:$ARTIFACTORY_KEY" -O 
